[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
async-recursion = "1.1.0"
async-trait = "0.1.80"
clap = { version = "4.5.4", features = ["derive", "env"] }
hex = "0.4.3"
notify-debouncer-mini = "0.4.1"
rayon = "1.10.0"
sha2 = "0.10.8"
sqlx = "0.7.4"
tokio = { version = "1.37.0", features = ["full"] }
